library(vcfR)
library(adegenet)
library(ape)
library(ggtree)
vcf <- read.vcfR("file.filter.vcf")
genind <- vcfR2genind(vcf)
dist_matrix <- dist(genvcfrind)
nj <- nj(dist_matrix)
write.tree(nj,"nj.newick")
